### ISSUE TITLE
Implement more elaborate Roadmap

### ISSUE THREAD

**Issue by VonSub** [threefoldfoundation/www_threefold.io#179]
To give a better insight into coming milestones, and provide a clear retrospect of the goals we met.
We want a more elaborate roadmap to be featured on the website, describing past, current, future events in greater detail. This will add to the credibility and will provide a moment of self-reflection for our team to see how many awesome things we've already accomplished.

Mockup already featured here: [staging/roadmap](https://www2.threefold.io/roadmap)

Requirements:

- [x] Must be Responsive
- [x] Must reflect the truth
- [x] Must cover both technical as commercial milestones
- [x] Content must be approved of as well from promo as tech team.

**Comment by despiegk** [comment]
how much work is it?

**Comment by VonSub** [comment]
We have the roadmap, it's a matter of content. We can defenitly do this in half a day depending on what milestones we want in there.

**Comment by VonSub** [comment]
@samaradel & @ehab-hassan I added some content. all 2019 content is not featured... limit to blocks?

**Comment by samaradel** [comment]
@VonSub fixed
