### ISSUE TITLE
Home page task list

### ISSUE THREAD

**Issue by danleighton** [threefoldfoundation/www_threefold.io#21]
**Source**

https://docs.google.com/document/d/1lWlMJgDLMyjpvS0b1tLqt3HzsVvyQpM8MHa5NkKtsOc/edit?ts=5b868c63#heading=h.i4v7wbkjxde7

On this page:
- [ ] Decide on whether banner goes at top, or above main content
- [ ] Remove all parts of page labelled to remove
- [ ] Leave those labelled leave
